### ISSUE TITLE
formAction creator vs Action Creator

### ISSUE THREAD

**Issue by tyteen4a03** [MiroslavPetrik/react-form-action#6]
Are there any guidance on when each one should be used?

**Comment by MiroslavPetrik** [comment]
Hey.

Short answer is that the `formAction` builder is preferred.

The reasons for it:
- handles input parsing with a schema
- handles error separately with the `.error()` method
- enables you to reuse code with middleware (`.use()`) method

the `createFormAction ` has only one benefit, that it will enable you to have standardized responses for the success, error, and invalid cases. This way you don't have to invent your own, which will keep your codebase clean.

The `formAction` uses the `createFormAction` internally.
